In [308]:
import os
import pandas as pd
import numpy as np
import statsmodels.formula.api as sm
import matplotlib.pyplot as plt

data = pd.read_csv("/Users/evilfantasies/workspace/AI_Linear_Regression/test/data.csv")

data

,zip_code,1998,2001,2004,2005,2006,2007,2010,2011,2012,2013,2014
0,20601,433388,528943,612853,645439,668446,703397,758051,768656,781967,787861,811719
1,20602,348017,397740,462102,475835,509938,547553,639590,667192,686028,695227,725015
2,20603,431102,563126,661844,702277,757255,819105,959395,988711,1013756,1044704,1075789
3,20606,6121,6872,7591,8517,7867,8675,9375,9799,9224,9282,9252
4,20607,165562,207530,283660,301893,315711,346189,411954,434862,448623,460857,477009
5,20608,15968,18336,21330,21669,25159,26349,26895,26729,27064,26294,25119
6,20609,18323,22617,23921,25532,28695,31472,33827,32964,34493,33481,36898
7,20611,21718,26359,34491,36202,31797,33469,35928,36699,36236,33992,36019
8,20613,170758,208618,288261,316151,345948,371622,448973,475215,487616,501550,520220
9,20615,7034,8506,12195,12201,13417,13726,13959,14344,14210,14464,16337
10,20616,88733,111161,138697,147950,151541,156117,176017,181520,189252,191288,200658
11,20617,27720,32711,39490,40455,41575,44098,39412,39599,41707,44394,41579
12,20618,11441,13662,15544,16696,16570,20434,20821,20608,20862,22672,22062
13,20619,157949,183806,237778,251352,280270,327840,390251,406179,435224,435374,462994
14,20620,20233,27682,34506,35355,39953,41287,47322,48234,49484,47678,48677
15,20621,22658,26948,34784,37123,40227,40373,42558,40641,41485,44010,46870
16,20622,80013,96525,123731,131027,138512,142617,147161,150861,150426,152205,158578
17,20623,54389,74296,94180,100613,99171,106296,116135,115705,118030,118804,119696
18,20624,17896,23233,29855,27962,32505,35135,38654,38867,40692,41113,42927
19,20626,6070,6432,7629,9045,8766,10950,14936,15039,13224,13365,14309
20,20628,10644,12364,16879,19880,20438,21264,21347,21777,22758,25989,28753
21,20630,8190,11362,15737,17771,17947,18931,26573,25109,27583,28963,27115
22,20632,7598,9506,11251,11810,12220,13607,14186,14001,13080,15448,16047
23,20634,90951,125792,159167,168740,182144,195434,227327,230373,231999,234505,237740
24,20636,164133,201130,257974,277549,287081,311140,365168,380177,404244,402600,413689
25,20637,89534,123080,163858,179198,186811,201703,209970,217555,225146,236937,231173
26,20639,302913,395169,480394,499712,558531,550723,572846,594215,629457,624644,644331
27,20640,139836,167196,199245,215411,230979,245927,266582,270668,267888,269517,272583
28,20645,16825,23329,41814,37728,38078,40583,36771,41460,40550,38327,39104
29,20646,375470,460299,583716,632635,645275,697490,711349,715277,731126,743390,788501
...,...,...,...,...,...,...,...,...,...,...,...,...
372,21830,49683,60104,78205,85254,87955,95200,98818,99925,101989,105907,112995
373,21835,7137,7812,8187,8765,9278,9073,8179,7689,8808,8016,8146
374,21837,29065,33644,42005,44677,48569,49797,51638,55887,50484,51311,54683
375,21838,21403,24900,30692,31325,32948,35716,36209,35034,33397,34138,35792
376,21840,6160,8298,8658,8058,8138,9544,9942,8112,9214,9577,9514
377,21841,13296,15913,18274,20126,20008,21020,21846,20548,22086,20689,22321
378,21842,243687,276822,387380,392997,369062,383600,342109,365428,378995,366613,398572
379,21849,46620,55030,59222,63997,66131,68264,65652,67428,69006,71028,76582
380,21850,29854,35804,43059,48578,49388,54359,54147,54423,55302,58258,60613
381,21851,94322,112180,120377,133978,136389,140256,139194,137796,142194,143253,144932
382,21853,85389,95393,111547,121781,133720,141941,134515,132662,139031,139494,143935
383,21856,14948,16493,20341,23605,22589,23113,22902,21931,22002,22869,23889
384,21863,69863,79159,87198,97098,98936,105816,103974,102742,107623,112242,113067
385,21864,8086,10218,10655,12522,11529,11667,11910,13418,12706,14183,14168
386,21865,6396,8210,9113,9626,9945,10099,10798,10220,10754,10429,12926
387,21869,12563,15077,15944,16449,16635,18449,17084,17129,18395,17867,18392
388,21871,23910,27160,30813,34595,36407,37193,35199,34258,37003,35353,38722
389,21872,8931,11615,12873,13548,13820,14232,15511,13852,15339,16657,16096
390,21874,27718,30262,36752,37541,39447,41520,43964,42346,44167,44682,44671
391,21875,69354,76594,98591,115980,120035,129726,129657,134246,137439,141128,148367
392,21901,215434,251219,314117,342824,369880,395251,415050,433326,453189,459836,485123
393,21903,84648,102271,123299,135588,139014,156814,155820,158862,158322,157822,159440
394,21904,99259,117749,152562,157865,166892,172198,182151,188624,191063,192986,205787
395,21911,149118,176519,220517,243914,251592,274608,271204,275816,280642,277730,289015
396,21912,23015,27392,37059,42313,35374,38670,36542,41977,38910,37537,40238
397,21915,71780,75753,87693,87578,100443,106057,110642,110810,113866,117779,108390
398,21917,36221,33800,59940,62720,65356,69265,69401,69635,72294,72187,74241
399,21918,69035,77816,88761,93859,95941,103867,106972,110540,112817,112574,116352
400,21919,46187,56785,64088,69661,76522,88312,75672,76440,79223,81639,81703
401,21921,640150,773832,875181,939406,967131,1051158,1045134,1054146,1089598,1104261,1143301

In [309]:
from sklearn.tree import DecisionTreeClassifier, export_graphviz

In [310]:
df2 = data.copy()

In [311]:
# df2.apply(lambda x: pd.to_numeric(x, downcast='float'))
df2 = df2.astype(float)
df2[:5]

,zip_code,1998,2001,2004,2005,2006,2007,2010,2011,2012,2013,2014
0,20601.0,433388.0,528943.0,612853.0,645439.0,668446.0,703397.0,758051.0,768656.0,781967.0,787861.0,811719.0
1,20602.0,348017.0,397740.0,462102.0,475835.0,509938.0,547553.0,639590.0,667192.0,686028.0,695227.0,725015.0
2,20603.0,431102.0,563126.0,661844.0,702277.0,757255.0,819105.0,959395.0,988711.0,1013756.0,1044704.0,1075789.0
3,20606.0,6121.0,6872.0,7591.0,8517.0,7867.0,8675.0,9375.0,9799.0,9224.0,9282.0,9252.0
4,20607.0,165562.0,207530.0,283660.0,301893.0,315711.0,346189.0,411954.0,434862.0,448623.0,460857.0,477009.0

In [312]:
df2.columns

Index(['zip_code', '1998', '2001', '2004', '2005', '2006', '2007', '2010',
       '2011', '2012', '2013', '2014'],
      dtype='object')

In [313]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()

In [314]:
classifier = le.fit_transform(df2['1998'])

In [315]:
le.inverse_transform([0,1,2,3,4,5,6,7,8,9,10])

array([ 3566.,  3992.,  4855.,  5099.,  5290.,  5908.,  5961.,  6014.,
        6070.,  6121.,  6145.])

In [316]:
dt = DecisionTreeClassifier()

In [317]:
dt.fit(df2.values, classifier)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [318]:
from IPython.display import Image

In [319]:
dt = DecisionTreeClassifier()

In [320]:
dt.fit(df2.values, classifier)
with open("dt.dot", 'w') as f:
    export_graphviz(dt, out_file=f, feature_names=df2.columns)

In [321]:
os.system('dot -Tpng dt.dot -o dt.png')

1

In [322]:
#Image(filename='dt.png')

In [323]:
#graph is too large! It overfitted to the data and was unable to create something useful

In [324]:
dt = DecisionTreeClassifier(max_depth = 100)

In [325]:
dt.fit(df2.values, classifier)
with open("dt.dot", 'w') as f:
    export_graphviz(dt, out_file=f, feature_names=df2.columns)

In [326]:
# part 2

data2 = pd.read_csv("/Users/evilfantasies/workspace/AI_Linear_Regression/test/data.csv")

In [327]:
data2[:5]

,zip_code,1998,2001,2004,2005,2006,2007,2010,2011,2012,2013,2014
0,20601,433388,528943,612853,645439,668446,703397,758051,768656,781967,787861,811719
1,20602,348017,397740,462102,475835,509938,547553,639590,667192,686028,695227,725015
2,20603,431102,563126,661844,702277,757255,819105,959395,988711,1013756,1044704,1075789
3,20606,6121,6872,7591,8517,7867,8675,9375,9799,9224,9282,9252
4,20607,165562,207530,283660,301893,315711,346189,411954,434862,448623,460857,477009

In [328]:
data2["mns_sqrt_root"] =  (data["1998"])**2 + (data["2001"])**2 + (data["2004"])**2 + (data["2005"])**2+ (data["2006"])**2 + (data["2007"])**2 + (data["2010"])**2  + (data["2011"])**2 + (data["2012"])**2 + (data["2013"])**2 + (data["2014"])**2

In [329]:
import math
data2["mns_sqrt_root"] = data2["mns_sqrt_root"].apply(lambda s: math.sqrt(s))

In [330]:
data2.head(5)

,zip_code,1998,2001,2004,2005,2006,2007,2010,2011,2012,2013,2014,mns_sqrt_root
0,20601,433388,528943,612853,645439,668446,703397,758051,768656,781967,787861,811719,2.293018e+06
1,20602,348017,397740,462102,475835,509938,547553,639590,667192,686028,695227,725015,1.900780e+06
2,20603,431102,563126,661844,702277,757255,819105,959395,988711,1013756,1044704,1075789,2.802316e+06
3,20606,6121,6872,7591,8517,7867,8675,9375,9799,9224,9282,9252,2.815577e+04
4,20607,165562,207530,283660,301893,315711,346189,411954,434862,448623,460857,477009,1.208968e+06

In [331]:
data2 = data2.astype(float)

In [332]:
data2[400:]

,zip_code,1998,2001,2004,2005,2006,2007,2010,2011,2012,2013,2014,mns_sqrt_root
400,21919.0,46187.0,56785.0,64088.0,69661.0,76522.0,88312.0,75672.0,76440.0,79223.0,81639.0,81703.0,2.432247e+05
401,21921.0,640150.0,773832.0,875181.0,939406.0,967131.0,1051158.0,1045134.0,1054146.0,1089598.0,1104261.0,1143301.0,3.258004e+06

In [333]:
classifier = le.fit_transform(data2['mns_sqrt_root'])

In [334]:
le.inverse_transform(range(0,402))

array([  1.50342227e+04,   1.71486614e+04,   1.97334504e+04,
         2.28313426e+04,   2.51363143e+04,   2.71268971e+04,
         2.75395737e+04,   2.76379502e+04,   2.78449904e+04,
         2.81557656e+04,   2.89100422e+04,   2.91850905e+04,
         2.92443048e+04,   3.08063887e+04,   3.08929667e+04,
         3.12778448e+04,   3.25920623e+04,   3.31278074e+04,
         3.55086336e+04,   3.77157122e+04,   3.78177682e+04,
         3.87880445e+04,   3.99296899e+04,   4.25809523e+04,
         4.32025875e+04,   4.51453998e+04,   4.56417936e+04,
         4.64948003e+04,   5.30704543e+04,   5.37311081e+04,
         5.41454276e+04,   5.57507985e+04,   6.11313028e+04,
         6.18402014e+04,   6.42151416e+04,   6.49541436e+04,
         6.57623280e+04,   6.82783839e+04,   6.90374510e+04,
         6.91832209e+04,   6.98882339e+04,   7.00130621e+04,
         7.13537877e+04,   7.13731154e+04,   7.14954335e+04,
         7.18078281e+04,   7.62425992e+04,   7.86208136e+04,
         7.95960088e+04,   8.24587043e+04,   8.35806631e+04,
         8.46515069e+04,   8.77227244e+04,   8.85475927e+04,
         8.99030090e+04,   8.99046248e+04,   9.04952777e+04,
         9.07443118e+04,   9.35549381e+04,   9.78329505e+04,
         9.89360709e+04,   9.89736144e+04,   9.97830386e+04,
         9.99964800e+04,   1.04583549e+05,   1.05077912e+05,
         1.05303996e+05,   1.06683164e+05,   1.07064742e+05,
         1.07946514e+05,   1.08942812e+05,   1.10460017e+05,
         1.10551219e+05,   1.12673988e+05,   1.13027030e+05,
         1.14096000e+05,   1.21154238e+05,   1.21694173e+05,
         1.21778313e+05,   1.22939993e+05,   1.23262424e+05,
         1.23615922e+05,   1.25856058e+05,   1.28036599e+05,
         1.31408105e+05,   1.31881799e+05,   1.32290229e+05,
         1.32590899e+05,   1.36287801e+05,   1.39041279e+05,
         1.39853654e+05,   1.40187853e+05,   1.43461901e+05,
         1.47322759e+05,   1.56644054e+05,   1.59919564e+05,
         1.66736813e+05,   1.80258912e+05,   1.81895473e+05,
         1.82757001e+05,   1.85618986e+05,   1.86331600e+05,
         1.88531254e+05,   1.90732726e+05,   1.92341978e+05,
         1.93285755e+05,   1.93841416e+05,   1.96868608e+05,
         1.96982668e+05,   2.00685500e+05,   2.04766474e+05,
         2.05207336e+05,   2.05280264e+05,   2.11340231e+05,
         2.15328115e+05,   2.16616309e+05,   2.19719122e+05,
         2.24802288e+05,   2.27388221e+05,   2.40301181e+05,
         2.43224676e+05,   2.45377679e+05,   2.49363044e+05,
         2.50015942e+05,   2.57899020e+05,   2.63993744e+05,
         2.69179788e+05,   2.71611743e+05,   2.76956942e+05,
         2.86901587e+05,   2.99246574e+05,   3.00666263e+05,
         3.05889505e+05,   3.07321354e+05,   3.12058528e+05,
         3.20209235e+05,   3.20436475e+05,   3.27865050e+05,
         3.28604573e+05,   3.31817249e+05,   3.31864452e+05,
         3.32707073e+05,   3.33093192e+05,   3.35232726e+05,
         3.36362980e+05,   3.36396838e+05,   3.41217613e+05,
         3.43296116e+05,   3.44985519e+05,   3.45883284e+05,
         3.49917268e+05,   3.53447802e+05,   3.73784748e+05,
         3.74331679e+05,   3.90012984e+05,   3.93707092e+05,
         3.98250931e+05,   4.00921045e+05,   4.13376213e+05,
         4.17110736e+05,   4.20584959e+05,   4.21357560e+05,
         4.28175000e+05,   4.30688951e+05,   4.38524767e+05,
         4.46842957e+05,   4.47480588e+05,   4.47918458e+05,
         4.50307209e+05,   4.50441474e+05,   4.50642320e+05,
         4.61352181e+05,   4.69082800e+05,   4.73313485e+05,
         4.77547421e+05,   4.90101938e+05,   5.12392477e+05,
         5.34131175e+05,   5.44232318e+05,   5.47533310e+05,
         5.53437213e+05,   5.58140687e+05,   5.60601235e+05,
         5.64117983e+05,   5.71407432e+05,   5.72199173e+05,
         5.82832558e+05,   5.96091468e+05,   6.16047440e+05,
         6.21863189e+05,   6.39841573e+05,   6.46668164e+05,
         6.47579834e+05,   6.48352621e+05,   6.70573355e+05,
         6.81073264e+05,   6.96614329e+05,   7.18783548e+05,
         7.25679428e+05,   7.27466796e+05,   7.52001092e+05,
         7.57521891e+05,   7.70950524e+05,   7.71234182e+05,
         7.76710020e+05,   7.77103903e+05,   7.81327384e+05,
         8.00840398e+05,   8.24428251e+05,   8.30225657e+05,
         8.32481480e+05,   8.38492086e+05,   8.41774723e+05,
         8.55734448e+05,   8.61120561e+05,   8.65130834e+05,
         8.80525660e+05,   8.84412595e+05,   9.11455392e+05,
         9.41983482e+05,   9.46060827e+05,   9.75105433e+05,
         9.77666452e+05,   9.88446471e+05,   1.00345717e+06,
         1.01460552e+06,   1.02553832e+06,   1.03203485e+06,
         1.03389848e+06,   1.04755370e+06,   1.06122633e+06,
         1.06396308e+06,   1.07922256e+06,   1.08698598e+06,
         1.08849208e+06,   1.08978707e+06,   1.12919892e+06,
         1.14717688e+06,   1.15757991e+06,   1.16096204e+06,
         1.16101454e+06,   1.17197783e+06,   1.18800570e+06,
         1.20896755e+06,   1.21083111e+06,   1.23450180e+06,
         1.25300534e+06,   1.27709311e+06,   1.30417223e+06,
         1.32695695e+06,   1.33932164e+06,   1.34320210e+06,
         1.36017833e+06,   1.36606557e+06,   1.37884831e+06,
         1.39946607e+06,   1.42188827e+06,   1.45206682e+06,
         1.45286576e+06,   1.45310713e+06,   1.46703816e+06,
         1.46922238e+06,   1.48397995e+06,   1.48765826e+06,
         1.49692261e+06,   1.50604550e+06,   1.51594268e+06,
         1.51840063e+06,   1.53922353e+06,   1.56048703e+06,
         1.56242602e+06,   1.62837095e+06,   1.64765429e+06,
         1.66341922e+06,   1.66585616e+06,   1.68290273e+06,
         1.68523043e+06,   1.69560407e+06,   1.70296018e+06,
         1.71999848e+06,   1.72456877e+06,   1.79623514e+06,
         1.84514125e+06,   1.84894519e+06,   1.85035461e+06,
         1.87297217e+06,   1.87845084e+06,   1.90077970e+06,
         1.95056067e+06,   1.99106922e+06,   2.01596662e+06,
         2.03763180e+06,   2.05626499e+06,   2.06421050e+06,
         2.06423289e+06,   2.14896685e+06,   2.16780651e+06,
         2.17329767e+06,   2.18602917e+06,   2.20462885e+06,
         2.22520935e+06,   2.22523387e+06,   2.22973471e+06,
         2.23829998e+06,   2.26013408e+06,   2.27739973e+06,
         2.29301810e+06,   2.29404394e+06,   2.31098351e+06,
         2.33505801e+06,   2.37204253e+06,   2.38616353e+06,
         2.39483319e+06,   2.41212233e+06,   2.42487918e+06,
         2.42921882e+06,   2.45725039e+06,   2.55321634e+06,
         2.57204042e+06,   2.58981688e+06,   2.59722831e+06,
         2.64416112e+06,   2.66000156e+06,   2.69190532e+06,
         2.70046517e+06,   2.71995295e+06,   2.73158897e+06,
         2.74133848e+06,   2.77577594e+06,   2.79044006e+06,
         2.79955606e+06,   2.80231624e+06,   2.81215214e+06,
         2.84757735e+06,   2.85149918e+06,   2.86648597e+06,
         2.86786218e+06,   2.93645912e+06,   2.95544232e+06,
         2.95851549e+06,   2.97057030e+06,   2.98075462e+06,
         3.06909006e+06,   3.14399011e+06,   3.14608895e+06,
         3.18990105e+06,   3.21357542e+06,   3.23231286e+06,
         3.24018157e+06,   3.25800416e+06,   3.26651846e+06,
         3.32183175e+06,   3.36402056e+06,   3.36800069e+06,
         3.39456334e+06,   3.39757124e+06,   3.39784045e+06,
         3.39818648e+06,   3.44676272e+06,   3.57835420e+06,
         3.64905535e+06,   3.66331824e+06,   3.68196035e+06,
         3.72791311e+06,   3.74477678e+06,   3.75292608e+06,
         3.79153218e+06,   3.84350717e+06,   3.86177213e+06,
         4.07855186e+06,   4.16752952e+06,   4.23571500e+06,
         4.32368143e+06,   4.33721497e+06,   4.37709043e+06,
         4.48787725e+06,   4.51498817e+06,   4.51918318e+06,
         4.68729816e+06,   4.74436620e+06,   5.15099546e+06,
         5.18933055e+06,   5.19820318e+06,   5.28510192e+06,
         5.31890218e+06,   5.43937370e+06,   5.46604693e+06,
         5.54295366e+06,   5.81243458e+06,   5.96788414e+06,
         6.11592272e+06,   6.18110626e+06,   6.43841023e+06,
         6.61602814e+06,   6.73949558e+06,   7.14800236e+06,
         7.15704247e+06,   7.22164737e+06,   9.01736976e+06,
         1.06205418e+07,   1.18263934e+07,   1.86952850e+07])

In [335]:
dt = DecisionTreeClassifier(max_depth = 20)

In [336]:
dt.fit(data2.values, classifier)
with open("dt.dot", 'w') as f:
    export_graphviz(dt, out_file=f, feature_names=data2.columns)

In [337]:
# Part 3

In [343]:
data3 = pd.read_csv("/Users/evilfantasies/Desktop/flipped_data.csv")

In [344]:
data3.head()

,zip_code,Totals,20601,20602,20603,20606,20607,20608,20609,20611,...,21901,21903,21904,21911,21912,21915,21917,21918,21919,21921
0,1998,116614285,433388,348017,431102,6121,165562,15968,18323,21718,...,215434,84648,99259,149118,23015,71780,36221,69035,46187,640150
1,2001,136235786,528943,397740,563126,6872,207530,18336,22617,26359,...,251219,102271,117749,176519,27392,75753,33800,77816,56785,773832
2,2004,155654521,612853,462102,661844,7591,283660,21330,23921,34491,...,314117,123299,152562,220517,37059,87693,59940,88761,64088,875181
3,2005,166297995,645439,475835,702277,8517,301893,21669,25532,36202,...,342824,135588,157865,243914,42313,87578,62720,93859,69661,939406
4,2006,177136975,668446,509938,757255,7867,315711,25159,28695,31797,...,369880,139014,166892,251592,35374,100443,65356,95941,76522,967131

In [346]:
data3 = data3.drop('zip_code',1)

In [347]:
data3 = data3.astype(float)

In [350]:
classifier = le.fit_transform(data3['Totals'])

In [352]:
le.inverse_transform(range(0,11))

array([  1.16614285e+08,   1.36235786e+08,   1.55654521e+08,
         1.66297995e+08,   1.77136975e+08,   1.89470912e+08,
         1.90616115e+08,   1.96896143e+08,   2.05257793e+08,
         2.05576901e+08,   2.14772916e+08])

In [353]:
dt = DecisionTreeClassifier()

In [354]:
dt.fit(data3.values, classifier)
with open("dt.dot", 'w') as f:
    export_graphviz(dt, out_file=f, feature_names=data3.columns)